DEFAULT_IGNORE_DIRS = {
    ".git", ".svn", ".hg",
    "node_modules", "__pycache__", ".pytest_cache", ".mypy_cache",
    "venv", ".venv", "env", ".env",
    "dist", "build", ".build", "out", "target",
    ".next", ".nuxt", ".output",
    "coverage", ".coverage",
    "logs", ".logs",
    "docs", "doc", "documentation",
    "examples", "example",
    "fixtures", "fixture",
    "stubs", "stub",
    "vendor",
    "tests", "test", "__tests__", "__test__",
    "spec", "specs", "e2e",
}

DEFAULT_IGNORE_FILES = {
    ".DS_Store", "Thumbs.db", ".gitkeep",
    "*.pyc", "*.pyo", "*.pyd",
    "*.o", "*.obj", "*.a", "*.lib", "*.so", "*.dll", "*.dylib",
    "*.exe", "*.bin",
    "*.png", "*.jpg", "*.jpeg", "*.gif", "*.bmp", "*.ico", "*.svg",
    "*.mp3", "*.mp4", "*.wav", "*.avi", "*.mov",
    "*.zip", "*.tar", "*.gz", "*.rar", "*.7z",
    "*.pdf", "*.doc", "*.docx", "*.xls", "*.xlsx",
    "*.lock", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "*.min.js", "*.min.css",
    "*.map",
    ".env", ".env.local", ".env.production", ".env.development",
    "*.promptpack.xml",
    "CHANGELOG", "CHANGELOG.*", "CHANGES", "CHANGES.*",
    "HISTORY", "HISTORY.*", "RELEASE*",
    "LICENSE", "LICENSE.*", "LICENCE", "LICENCE.*",
    "AUTHORS", "AUTHORS.*", "CONTRIBUTORS", "CONTRIBUTORS.*",
    "NOTICE", "NOTICE.*", "PATENTS",
    "*.rst",
    "*.txt",
}

LANGUAGE_MAP = {
    ".py": "py",
    ".js": "js",
    ".ts": "ts",
    ".jsx": "jsx",
    ".tsx": "tsx",
    ".mjs": "js",
    ".cjs": "js",
    ".java": "java",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "h",
    ".hpp": "hpp",
    ".cs": "cs",
    ".go": "go",
    ".rs": "rs",
    ".rb": "rb",
    ".php": "php",
    ".swift": "swift",
    ".kt": "kt",
    ".scala": "scala",
    ".r": "r",
    ".lua": "lua",
    ".dart": "dart",
    ".html": "html",
    ".htm": "html",
    ".css": "css",
    ".scss": "scss",
    ".sass": "sass",
    ".less": "less",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".xml": "xml",
    ".md": "md",
    ".mdx": "mdx",
    ".sh": "sh",
    ".bash": "sh",
    ".zsh": "sh",
    ".fish": "sh",
    ".ps1": "ps1",
    ".sql": "sql",
    ".graphql": "gql",
    ".gql": "gql",
    ".proto": "proto",
    ".dockerfile": "docker",
    ".tf": "tf",
    ".hcl": "hcl",
    ".nix": "nix",
    ".vim": "vim",
    ".env.example": "env",
}

MAX_FILE_BYTES = 512 * 1024

